ALTER TABLE PAYMENT_DETAILS DROP payer_id;
ALTER TABLE TRANSACTIONS DROP "method";

ALTER TABLE PAYMENT_DETAILS ADD payer_method VARCHAR(255);
ALTER TABLE PAYMENT_DETAILS ADD split_method VARCHAR(255);
